version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_api
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_api
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: